# on:
#   workflow_run:
#     workflows: ["Setup Flask app infrastructure"]
#     branches: [main]
#     types: 
#       - completed

# name: Deploy Flask app to Azure

# env:
#   REGISTRY_LOGIN_SERVER: 
#   IMAGE_BASE_NAME: wh-flask-demo

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: 'Login via Azure CLI'
#       uses: azure/login@v1
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}
#     - uses: azure/webapps-deploy@v2
#       with:
#         app-name: 'wh-flask-demo'
#         images: '${{ env.REGISTRY_LOGIN_SERVER }}/${{env.IMAGE_BASE_NAME}}:latest'