# on: [push]

# name: Deploy Flask app to Azure

# env:
#   RESOURCE_GROUP_DEV: aguadamillas_students_1
#   SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
#   REGISTRY_LOGIN_SERVER: 
#   IMAGE_BASE_NAME: wh-flask-demo

# jobs:
#   build-and-publish:
#     runs-on: ubuntu-latest
#     steps:
#     # checkout the repo
#     - name: 'Checkout Github Action'
#       uses: actions/checkout@main

#     - name: 'Login via Azure CLI'
#       uses: azure/login@v1
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}

#     - uses: azure/docker-login@v1
#       with:
#         login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
#         username: ${{ secrets.REGISTRY_USERNAME }}
#         password: ${{ secrets.REGISTRY_PASSWORD }}

#     # - name: 'Get docker registry credentials from Azure Key Vault'
#     #   uses: azure/CLI@v1
#     #   with:
#     #   inlineScript: |
#     #    echo "REGISTRY_USERNAME=$(az keyvault secret show --name ${{ env.KEY_VAULT_SECRET_NAME_ACR_USERNAME }} --vault-name ${{ env.KEY_VAULT_NAME }} --query value -o tsv)" >> $GITHUB_ENV
#     #    echo "REGISTRY_PASSWORD=$(az keyvault secret show --name ${{ env.KEY_VAULT_SECRET_NAME_ACR_PASSWORD }} --vault-name ${{ env.KEY_VAULT_NAME }} --query value -o tsv)" >> $GITHUB_ENV

#     - name: Set image version
#       id: image-version
#       run: echo "::set-output name=version::$(echo ${GITHUB_REF#refs/heads/})-$(date +'%Y.%m.%d.%H.%M')"

#     - name: 'Build and push image'
#       working-directory: ./app
#       run: |
#         docker build . -t ${{ env.REGISTRY_LOGIN_SERVER }}/${{env.IMAGE_BASE_NAME}}:${{ steps.image-version.outputs.version }}
#         docker build . -t ${{ env.REGISTRY_LOGIN_SERVER }}/${{env.IMAGE_BASE_NAME}}:latest
#         docker push ${{ env.REGISTRY_LOGIN_SERVER }}/${{env.IMAGE_BASE_NAME}}:${{ steps.image-version.outputs.version }}
#         docker push ${{ env.REGISTRY_LOGIN_SERVER }}/${{env.IMAGE_BASE_NAME}}:latest

#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: 'Login via Azure CLI'
#       uses: azure/login@v1
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}
#     - uses: azure/webapps-deploy@v2
#       with:
#         app-name: 'wh-flask-demo'
#         images: '${{ env.REGISTRY_LOGIN_SERVER }}/${{env.IMAGE_BASE_NAME}}:latest'